# 2_Dynamic_Parrot
service: kbh-lambda-post-msg-<<YOUR NUMBER>>
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2

functions:
  api:
    handler: index.handler
    url:
      cors: true
    timeout: 900
    memorySize: 1024
